# Generated by Django 5.2.5 on 2025-10-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_called_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Не обработан'), ('in_progress', 'В сборке'), ('in_delivery', 'В доставке'), ('completed', 'Завершён')], db_index=True, default='accepted', max_length=50, verbose_name='Статус'),
        ),
    ]
