# Generated by Django 5.2.5 on 2025-10-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_order_address_alter_order_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('web_cash', 'Электронно')], db_index=True, max_length=30, verbose_name='Способ оплаты'),
        ),
    ]
