# Generated by Django 5.2.5 on 2025-10-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoordapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='request',
        ),
        migrations.AddField(
            model_name='place',
            name='updated_at',
            field=models.TimeField(auto_now=True, verbose_name='Время обновления'),
        ),
    ]
